### ISSUE TITLE
Panic in UnmarshalText() when input has a certain form.

### ISSUE THREAD

**Issue by andreicalin** [satori/go.uuid#20]
`UnmarshalText()` panics when input is exactly 32 bytes long and of the form 

`xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx`

Example program:
```go
package main

import (
        "github.com/satori/go.uuid"
        "fmt"
)

func main() {
        s36 := "7f31b5e7-83ee-404e-a278-f2cd3220aaaa"
        s35 := "7f31b5e7-83ee-404e-a278-f2cd3220aaa"
        s34 := "7f31b5e7-83ee-404e-a278-f2cd3220aa"
        s33 := "7f31b5e7-83ee-404e-a278-f2cd3220a"
        s32 := "7f31b5e7-83ee-404e-a278-f2cd3220"

        fmt.Println(uuid.FromString(s36))
        fmt.Println(uuid.FromString(s35))
        fmt.Println(uuid.FromString(s34))
        fmt.Println(uuid.FromString(s33))
        fmt.Println(uuid.FromString(s32)) // will panic
}
```

Output:

```
uuidcrash$ ./uuidcrash 
7f31b5e7-83ee-404e-a278-f2cd3220aaaa <nil>
7f31b5e7-83ee-404e-a278-f2cd3220aa00 encoding/hex: invalid byte: U+0000
7f31b5e7-83ee-404e-a278-f2cd3220aa00 encoding/hex: invalid byte: U+0000
7f31b5e7-83ee-404e-a278-f2cd32200000 encoding/hex: invalid byte: U+0000
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x5310c0, 0xc82000a0f0)
        /home/acln/go/src/runtime/panic.go:464 +0x3e6
github.com/satori/go%2euuid.(*UUID).UnmarshalText(0xc820047db0, 0xc82000e2d3, 0x8, 0x8, 0x0, 0x0)
        /home/acln/w/go/src/github.com/satori/go.uuid/uuid.go:247 +0x481
github.com/satori/go%2euuid.FromString(0x583520, 0x20, 0x4e40ee83e7b5317f, 0x78a2, 0x0, 0x0)
        /home/acln/w/go/src/github.com/satori/go.uuid/uuid.go:321 +0x97
main.main()
        /home/acln/w/go/src/github.com/andreicalin/uuidcrash/main.go:19 +0x6ba
```

I've investigated the cause of the panic.

In [`UnmarshalText()`](https://github.com/andreicalin/go.uuid/blob/e673fdd4dea8a7334adbbe7f57b7e4b00bdc5502/uuid.go#L228), when `len(text) > 32 && len(text) < 36`, `cap(text) == 48`. Therefore, in the final [call to `hex.Decode()`](https://github.com/andreicalin/go.uuid/blob/e673fdd4dea8a7334adbbe7f57b7e4b00bdc5502/uuid.go#L247), the access `text[:byteGroup]` does not panic, even if `byteGroup > len(text)`, because `byteGroup < cap(text)`.

However, when `len(text) == 32`, `cap(text) == 32`. In this case, accessing `text[:byteGroup]` with `byteGroup > len(text)` causes the panic.

**Comment by dim** [comment]
:+1:
